web/conversation/urls.py
from django.urls import path
from . import views

#plik odpowiadający za adresy url na stronie które wywołują funkcje z pliku views.py

app_name = 'conversation'  #nazwa podaplikacji
urlpatterns = [    #adresy url na stronie odpowiadające za wywołanie funkcji z pliku views.py
    path('new/<int:item_pk>/', views.new_conversations, name='new'),
    path('inbox/', views.inbox, name='inbox'),
    path('detail/<int:conversation_pk>/', views.detail, name='detail'),
]

web/item/urls.py
from django.urls import path
from . import views

#plik odpowiadający za adresy url na stronie które wywołują funkcje z pliku views.py

app_name = 'item'#nazwa podaplikacji
urlpatterns = [#adresy url na stronie odpowiadające za wywołanie funkcji z pliku views.py
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('category/<int:pk>/',views.category,name='category'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('browse/', views.browse, name='browse')
]

web/web/urls.py
from django.conf import settings
from django.conf.urls.static import static  #nie robić tego w produkcji

from django.contrib import admin
from django.urls import path, include
from core.views import index,contact

urlpatterns = [
    path('', include('core.urls')),#podaplikacja core gdzie odsyłamy do pliku urls.py z core
    path('items/', include('item.urls')), #podaplikacja items gdzie odsyłamy do pliku urls.py z item
    path('dashboard/', include('dashboard.urls')), #podaplikacja dashboard gdzie odsyłamy do pliku urls.py z dashboard
    path('inbox/', include('conversation.urls')), #podaplikacja conversation gdzie odsyłamy do pliku urls.py z conversation
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #nie robić tego w produkcji

web/item/models.py
from django.db import models
from django.contrib.auth.models import User


#modele odpowiadające tabelom w bazie danych

class Category(models.Model):#model kategorii
    name = models.CharField(max_length=255)

    class Meta:#klasa odpowiadająca za wyświetlanie kategorii w panelu admina
        ordering = ('name',)
        verbose_name_plural = 'categories'

    def __str__(self):#funkcja odpowiadająca za wyświetlanie nazwy kategorii
        return self.name
    
class Item(models.Model):#model przedmiotu
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category,related_name='items',on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images',blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User,related_name='items',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


    class Meta:#klasa odpowiadająca za wyświetlanie przedmiotów w panelu admina
        ordering = ('name',)

    def __str__(self):#funkcja odpowiadająca za wyświetlanie nazwy przedmiotu
        return self.name

web/item/forms.py
from django import forms
from .models import Item

TEXT_INPUT = 'w-full py-4 px-6 rounded-xl border'
class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'category','description', 'price', 'image']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Name', 'class': TEXT_INPUT}),
            'category': forms.Select(attrs={'placeholder': 'Category', 'class': TEXT_INPUT}),
            'description': forms.Textarea(attrs={'placeholder': 'Description', 'class': TEXT_INPUT}),
            'price': forms.NumberInput(attrs={'placeholder': 'Price', 'class': TEXT_INPUT}),
            'image': forms.FileInput(attrs={'placeholder': 'Image', 'class': TEXT_INPUT}),
        }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'category','description', 'price', 'image','is_sold']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Name', 'class': TEXT_INPUT}),
            'category': forms.Select(attrs={'placeholder': 'Category', 'class': TEXT_INPUT}),
            'description': forms.Textarea(attrs={'placeholder': 'Description', 'class': TEXT_INPUT}),
            'price': forms.NumberInput(attrs={'placeholder': 'Price', 'class': TEXT_INPUT}),
            'image': forms.FileInput(attrs={'placeholder': 'Image', 'class': TEXT_INPUT}),
            'is_sold': forms.CheckboxInput(attrs={'placeholder': 'Is sold', 'class': TEXT_INPUT + 'text-left'}),
        }

web/item/views.py
# Create your views here.
from django.shortcuts import render,get_object_or_404,redirect
from .models import Item,Category
from django.contrib.auth.decorators import login_required
from .forms import NewItemForm,EditItemForm
from django.db.models import Q


def detail(request,pk):#funkcja odpowiadająca za wyświetlanie strony z danymi przedmiotu
    
    item=get_object_or_404(Item,pk=pk)#pobranie przedmiotu z bazy danych
    related_items=Item.objects.filter(category=item.category, is_sold=False).exclude(pk=item.pk)#pobranie przedmiotów z tej samej kategorii
    return render(request, 'item/detail.html', {'item': item, 'related_items': related_items})#wyświetlenie strony z danymi przedmiotu

def category(request,pk):#funkcja odpowiadająca za wyświetlanie strony z przedmiotami z danej kategorii
    category=get_object_or_404(Category,pk=pk)#pobranie kategorii z bazy danych
    items=Item.objects.filter(category=category, is_sold=False)#pobranie przedmiotów z danej kategorii
    related_categories=Category.objects.exclude(pk=category.pk)#pobranie kategorii z wyłączeniem kategorii z której pobierane są przedmioty
    return render(request, 'item/category.html', {'items': items, 'category': category,'related_categories':related_categories})#wyświetlenie strony z przedmiotami z danej kategorii


def browse(request):#funkcja odpowiadająca za wyświetlanie strony z wszystkimi przedmiotami
    
    query=request.GET.get('query','')#pobranie zapytania z adresu url
    category_id=request.GET.get('category',0)#pobranie id kategorii z adresu url
    max_price=request.GET.get('max_price','')#pobranie maksymalnej ceny z adresu url
    min_price=request.GET.get('min_price','')#pobranie minimalnej ceny z adresu url
    items=Item.objects.filter(is_sold=False)#pobranie przedmiotów z bazy danych
    
    categories=Category.objects.all()#pobranie kategorii z bazy danych
    if int(category_id) != 0:
        items=items.filter(category_id=category_id)
    if query:
        items=items.filter(Q(name__icontains=query)|Q(description__icontains=query))
    if max_price or min_price:
        if max_price and min_price:
            items=items.filter(price__range=(min_price,max_price))
        elif max_price:
            items=items.filter(price__lte=max_price)
        elif min_price:
            items=items.filter(price__gte=min_price)
    return render(request, 'item/browse.html', {'items': items,'categories':categories,'query':query,'category_id':int(category_id)})#wyświetlenie strony z przedmiotami



@login_required
def new(request):  #funkcja odpowiadająca za wyświetlanie strony z formularzem dodawania nowego przedmiotu
    if request.method == 'POST':   
        form = NewItemForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            return redirect('item:detail', pk=item.id)
    else:
        form=NewItemForm()
    return render(request, 'item/new.html', {'form':form})   #wyświetlenie strony z formularzem dodawania nowego przedmiotu  

@login_required
def delete(request,pk):
    item = get_object_or_404(Item, pk=pk,created_by=request.user)
    item.delete()
    return redirect('dashboard:index')

@login_required
def edit(request,pk):  #funkcja odpowiadająca za wyświetlanie strony z formularzem dodawania nowego przedmiotu
    item = get_object_or_404(Item, pk=pk,created_by=request.user)
    if request.method == 'POST':   
        form = EditItemForm(request.POST, request.FILES,instance=item)
        if form.is_valid():
            form.save()
            return redirect('item:detail', pk=item.id)
    else:
        form=EditItemForm(instance=item)
    return render(request, 'item/edit.html', {'form':form})   #wyświetlenie strony z formularzem dodawania nowego przedmiotu  

web/item/templates/item/browse.html
{% extends 'core/base.html' %} <!-- Rozszerza bazowy szablon HTML -->
{% block title %}Home{%endblock%} <!-- Ustawia tytuł strony na "Home" -->

{%block content%} <!-- Początek bloku zawartości -->
    <div class="grid grid-cols-4 gap-4">
        
        <div class="col-span-1 mt-6 px-6 py-12 bg-gray-200 rounded-xl"> <!--side bar -->
            
            <form method="get" action="{% url 'item:browse' %}">
                <input name="category" type="hidden" value="{{category_id}}">
                <input name="min_price" type="hidden" value="{{min_price}}">
                <input name="max_price" type="hidden" value="{{max_price}}">
                <input name="query" class="w-full px-6 py-4 mb-4 border border-gray-300 rounded-lg" type="text" placeholder="Search for items" value="{{query}}"> <!-- Pole wyszukiwania -->
                <button class="mt-2 px-8 py-4 bg-teal-500 text-white rounded-xl inline-block">Search</button> <!-- Przycisk wyszukiwania -->
            </form>

            <hr class="my-6 border-t-2 border-gray-300"> <!-- Linia oddzielająca -->

            <p class="text-xl font-semibold">Categories</p> <!-- Nagłówek kategorii -->
            
            <ul class="mt-4 space-y-2"> <!-- Lista kategorii -->
                {% for category in categories %} <!-- Pętla przez kategorie -->
                <li class=" py-2 px-2 rounded-xl {% if category.id == category_id %} bg-gray-300 {% endif %}"> <!-- Element listy -->
                    <a href="{% url 'item:browse' %}?query={{query}}&category={{category.id}}">{{category.name}}</a> <!-- Link do przeglądania przedmiotów w danej kategorii -->
                </li>
                {% endfor %} <!-- Koniec pętli przez kategorie -->
            </ul>

            <hr class="my-6 border-t-2 border-gray-300"> <!-- Linia oddzielająca -->
            <p class="text-xl font-semibold">Price Range</p> <!-- Nagłówek zakresu cen -->
            <br>
            <form method="get" action="{% url 'item:browse' %}">
                <input name="query" type="hidden" value="{{query}}">
                <input name="category" type="hidden" value="{{category_id}}">
                <input name="min_price" class="w-full px-6 py-4 mb-4 border border-gray-300 rounded-lg" type="number" placeholder="Min Price" value="{{min_price}}" min="0"> <!-- Pole na minimalną cenę -->
                <input name="max_price" class="w-full px-6 py-4 mb-4 border border-gray-300 rounded-lg" type="number" placeholder="Max Price" value="{{max_price}}" min="0"> <!-- Pole na maksymalną cenę -->
                <button class="mt-2 px-8 py-4 bg-teal-500 text-white rounded-xl inline-block">Filter</button> <!-- Przycisk filtrowania -->
            </form>
            <hr class="my-6 border-t-2 border-gray-300"> <!-- Linia oddzielająca -->
            <p class="text-xl font-semibold">Clear</p> <!-- Nagłówek kategorii -->
            <br>
            <ul>
                <li><a href="{% url 'item:browse' %}" class="mt-2 mb-4 px-8 py-4 bg-teal-500 text-white rounded-xl inline-block">Clear Filters</a></li>
            </ul>
        
        </div>
        
        
        
        <div class="col-span-3 mt-6 px-6 py-12 bg-gray-100 rounded-xl"> <!-- Kontener dla najnowszych przedmiotów -->
            <h2 class="mb-12 text-2xl text-center">Browsed Items</h2> <!-- Nagłówek sekcji -->
            <div class="grid grid-cols-3 gap-3"> <!-- Kontener siatki dla przedmiotów -->
                {% for item in items %} <!-- Pętla przez wszystkie przedmioty -->
                <div> <!-- Kontener dla pojedynczego przedmiotu -->
                    <a href="{% url 'item:detail' item.id %}"> <!-- Link do szczegółów przedmiotu -->
                        <div>
                            <img src= "{{item.image.url}}" class="rounded-t-xl" style="width: 100%; height: 200px; object-fit: cover; display: block; margin: auto;"> <!-- Obraz przedmiotu -->
                        </div>
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{item.name}}</h2> <!-- Nazwa przedmiotu -->
                            <p class="text-gray-500">Price: {{item.price}} $</p> <!-- Cena przedmiotu -->
                        </div>
                    </a>
                </div>
                {% endfor %} <!-- Koniec pętli przez przedmioty -->
            </div>
        </div>
    </div>

{%endblock%} <!-- Koniec bloku zawartości -->

web/item/templates/item/category.html
{% extends 'core/base.html' %} <!-- Rozszerza bazowy szablon HTML -->
{% block title %}Home{%endblock%} <!-- Ustawia tytuł strony na "Home" -->

{%block content%} <!-- Początek bloku zawartości -->
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl"> <!-- Kontener dla najnowszych przedmiotów -->
        <h2 class="mb-12 text-2xl text-center">{{category.name}}</h2> <!-- Nagłówek sekcji -->
        
        <div class="grid grid-cols-3 gap-3"> <!-- Kontener siatki dla przedmiotów -->
            {% for item in items %} <!-- Pętla przez wszystkie przedmioty -->
            <div> <!-- Kontener dla pojedynczego przedmiotu -->
                <a href="{% url 'item:detail' item.id %}"> <!-- Link do szczegółów przedmiotu -->
                    <div>
                        <img src= "{{item.image.url}}" class="rounded-t-xl" style="width: 100%; height: 200px; object-fit: cover; display: block; margin: auto;"> <!-- Obraz przedmiotu -->
                    </div>
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{item.name}}</h2> <!-- Nazwa przedmiotu -->
                        <p class="text-gray-500">Price: {{item.price}} $</p> <!-- Cena przedmiotu -->
                    </div>
                </a>
            </div>
            {% endfor %} <!-- Koniec pętli przez przedmioty -->
        </div>
    </div>
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl"> <!-- Kontener dla kategorii -->
        <h2 class="mb-12 text-2xl text-center">Categories</h2> <!-- Nagłówek sekcji -->
        <div class="grid grid-cols-3 gap-3"> <!-- Kontener siatki dla kategorii -->
            {% for category in related_categories %} <!-- Pętla przez wszystkie kategorie -->
            <div> <!-- Kontener dla pojedynczej kategorii -->
                <a href="{% url 'item:category' category.id %}">
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{category.name}}</h2> <!-- Nazwa kategorii -->
                        <p class="text-gray-500">{% if category.items.count == 1 %}1 item{% else %}{{category.items.count}} items{% endif %}</p> <!-- Liczba przedmiotów w kategorii -->
                    </div>
                </a>
            </div>
            {% endfor %} <!-- Koniec pętli przez kategorie -->
        </div>
    </div>

{%endblock%} <!-- Koniec bloku zawartości -->

web/item/templates/item/detail.html
{% extends 'core/base.html' %} <!-- Rozszerza bazowy szablon HTML -->
<!-- Początek bloku tytułu -->
{% block title %} 
    {{item.name|capfirst}} 
{% endblock %} 
<!-- Koniec bloku tytułu -->

{% block content %} <!-- Początek bloku zawartości -->
    <div class="grid grid-cols-5 gap-6"> <!-- Kontener siatki dla szczegółów przedmiotu i powiązanych przedmiotów -->
        <div class="col-span-3"> <!-- Kontener dla obrazu przedmiotu -->
            <img src="{{item.image.url}}" class="rounded-xl" style="width: 100%; height: 500px;"> <!-- Obraz przedmiotu -->
        </div>
        <div class="col-span-2 p-6 bg-gray-100 rounded-xl"> <!-- Kontener dla szczegółów przedmiotu -->
            <h1 class="text-3xl font-bold">{{item.name}}</h1> <!-- Nazwa przedmiotu -->
            <p class="text-xl font-semibold text-gray-500">{{item.price}} $ </p> <!-- Cena przedmiotu -->
            <p class="text-lg font-semibold text-gray-500"><strong>Category: </strong>{{item.category}}</p> <!-- Kategoria przedmiotu -->
            <p class="text-lg font-semibold text-gray-500"><strong>Seller: </strong>{{item.created_by}}</p><br> <!-- Sprzedawca przedmiotu -->
            
            
            {% if item.description %} <!-- Jeśli przedmiot ma opis -->
                <p class="text-lg text-gray-700">
                    <strong class="text-gray-500 font-semibold">Description:</strong><br> <!-- Nagłówek "Description" -->
                    {{item.description}} <!-- Opis przedmiotu -->
                </p>
            {% endif %}
                
            

            
            {% if request.user == item.created_by %}
                <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold text-white bg-teal-500 rounded-xl hover:bg-teal-700">Edit item</a> <!-- Przycisk "Edit item" -->
                <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold text-white bg-red-500 rounded-xl hover:bg-red-700" onclick="confirmDelete(event);">Delete item</a>   
                
            {% else %}
            <a href="{% url 'conversation:new'  item.id%}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold text-white bg-teal-500 rounded-xl hover:bg-teal-700">Contact seller</a> <!-- Przycisk "Contact seller" -->
            {% endif %}
                
        </div>
    </div>
    <br>
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl"> <!-- Kontener dla powiązanych przedmiotów -->
        <h2 class="mb-12 text-2xl text-center">Related Items</h2> <!-- Nagłówek "Related Items" -->
        
        <div class="grid grid-cols-3 gap-3"> <!-- Kontener siatki dla powiązanych przedmiotów -->
            {% for item in related_items %} <!-- Pętla przez powiązane przedmioty -->
            <div> <!-- Kontener dla pojedynczego powiązanego przedmiotu -->
                <a href="{% url 'item:detail' item.id %}"> <!-- Link do szczegółów powiązanego przedmiotu -->
                    <div>
                        <img src= "{{item.image.url}}" class="rounded-t-xl" style="width: 100%; height: 200px; object-fit: cover; display: block; margin: auto;"><!-- Obraz powiązanego przedmiotu -->
                    </div>
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{item.name}}</h2> <!-- Nazwa powiązanego przedmiotu -->
                        <p class="text-gray-500">Price: {{item.price}} $</p> <!-- Cena powiązanego przedmiotu -->
                    </div>
                </a>
            </div>
            {% endfor %} <!-- Koniec pętli przez powiązane przedmioty -->
        </div>
    </div>  
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        function confirmDelete(event) {
            event.preventDefault();
            var url = event.currentTarget.href;
            swal({
                title: "Are you sure?",
                text: "Once deleted, you will not be able to recover this item!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
                if (willDelete) {
                    window.location.href = url;
                }
            });
        }
    </script>
{% endblock %} <!-- Koniec bloku zawartości -->

web/item/templates/item/edit.html
{% extends 'core/base.html' %}

{% block title %}
    {{item.name|capfirst}} Edit
{% endblock  %}

{%block content %}
    <h1 class="mb-6 text-3xl">{{title}}</h1>
    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        <div class="space-y-4">
            {{form.as_p}}
        </div>
        {% if form.errors or form.non_field_errors %} <!-- Jeśli są błędy formularza -->
                <div class="bg-red-100 p-6 mb-3 rounded-xl text-left"> <!-- Kontener dla błędów -->
                    <ul> <!-- Lista błędów -->
                        {% for error in form.errors %} <!-- Pętla przez błędy -->
                            <li>{{error}}</li> <!-- Wyświetla błąd -->
                        {% endfor %}
                    </ul>
                </div>
        {% endif %}
        <button class="mt-6 py-4 px-8 text-lg rounded-xl bg-teal-500 hover:bg-teal-700 text-white">Edit</button> <!-- Przycisk zapisu -->
    </form>
{% endblock  %}
```
    

web/item/templates/item/new.html
{% extends 'core/base.html' %}

{% block title %}
    {{title}}
{% endblock  %}

{%block content %}
    <h1 class="mb-6 text-3xl">{{title}}</h1>
    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        <div class="space-y-4">
            {{form.as_p}}
        </div>
        {% if form.errors or form.non_field_errors %} <!-- Jeśli są błędy formularza -->
                <div class="bg-red-100 p-6 mb-3 rounded-xl"> <!-- Kontener dla błędów -->
                    <ul> <!-- Lista błędów -->
                        {% for error in form.errors %} <!-- Pętla przez błędy -->
                            <li>{{error}}</li> <!-- Wyświetla błąd -->
                        {% endfor %}
                    </ul>
                </div>
        {% endif %}
        <button class="mt-6 py-4 px-8 text-lg rounded-xl bg-teal-500 hover:bg-teal-700 text-white">Create</button> <!-- Przycisk zapisu -->
    </form>
{% endblock  %}
```
    