web/conversation/urls.py
from django.urls import path
from . import views

#plik odpowiadający za adresy url na stronie które wywołują funkcje z pliku views.py

app_name = 'conversation'  #nazwa podaplikacji
urlpatterns = [    #adresy url na stronie odpowiadające za wywołanie funkcji z pliku views.py
    path('new/<int:item_pk>/', views.new_conversations, name='new'),
    path('inbox/', views.inbox, name='inbox'),
    path('detail/<int:conversation_pk>/', views.detail, name='detail'),
]

web/core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm
app_name = 'core' #nazwa podaplikacji

urlpatterns = [ #adresy url na stronie odpowiadające za wywołanie funkcji z pliku views.py
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm), name='login'),
]

web/dashboard/urls.py
from django.urls import path
from . import views
app_name = 'dashboard' #nazwa podaplikacji

urlpatterns = [ #adresy url na stronie odpowiadające za wywołanie funkcji z pliku views.py
    path('', views.index, name='index'),
    
]

web/item/urls.py
from django.urls import path
from . import views

#plik odpowiadający za adresy url na stronie które wywołują funkcje z pliku views.py

app_name = 'item'#nazwa podaplikacji
urlpatterns = [#adresy url na stronie odpowiadające za wywołanie funkcji z pliku views.py
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('category/<int:pk>/',views.category,name='category'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('browse/', views.browse, name='browse')
]

web/web/urls.py
from django.conf import settings
from django.conf.urls.static import static  #nie robić tego w produkcji

from django.contrib import admin
from django.urls import path, include
from core.views import index,contact

urlpatterns = [
    path('', include('core.urls')),#podaplikacja core gdzie odsyłamy do pliku urls.py z core
    path('items/', include('item.urls')), #podaplikacja items gdzie odsyłamy do pliku urls.py z item
    path('dashboard/', include('dashboard.urls')), #podaplikacja dashboard gdzie odsyłamy do pliku urls.py z dashboard
    path('inbox/', include('conversation.urls')), #podaplikacja conversation gdzie odsyłamy do pliku urls.py z conversation
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #nie robić tego w produkcji

web/core/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class LoginForm(AuthenticationForm):#form do logowania na stronie
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Your Username', 'class': 'w-full p-2 my-2 mx-5 border border-gray-300 rounded-xl'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Your Password', 'class': 'w-full p-2 my-2 mx-5 border border-gray-300 rounded-xl'}))




class SignupForm(UserCreationForm):#form do rejestracji na stronie
    class Meta:#klasa do formularza
        model = User
        fields = ['username', 'email', 'password1', 'password2']
    #widgety do rejestracji    
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Your Username', 'class': 'w-full p-2 my-2 mx-5 border border-gray-300 rounded-xl'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Your Email', 'class': 'w-full p-2 my-2 mx-5 border border-gray-300 rounded-xl'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Your Password', 'class': 'w-full p-2 my-2 mx-5 border border-gray-300 rounded-xl'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password', 'class': 'w-full p-2 my-2 mx-5 border border-gray-300 rounded-xl'}))

web/core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from .forms import SignupForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
# Create your views here.
# funkcje odpowiadające za wyświetlanie stron wywyują się po wpisaniu odpowiedniego adresu url z pliku urls.py
def index(request):#funkcja odpowiadająca za wyświetlanie strony głównej
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    return render(request, 'core/index.html', {'items': items, 'categories': categories})

def contact(request):#funkcja odpowiadająca za wyświetlanie strony kontaktowej
    return render(request, 'core/contact.html')

def signup(request):#funkcja odpowiadająca za wyświetlanie strony rejestracji
    if request.method == 'POST':#jeżeli metoda jest POST to wywołaj formularz
        form = SignupForm(request.POST)#formularz
        if form.is_valid():
            form.save()
        return redirect('/login/')#przekierowanie na stronę logowania
    else:
        form = SignupForm()
    return render(request, 'core/signup.html', {'form': form})#wyświetlenie strony rejestracji


def logout_view(request):#funkcja odpowiadająca za wylogowanie
    if request.method == 'POST':
        logout(request)
        return redirect('/')
    return render(request, 'core/logout.html')#wyświetlenie strony wylogowania

web/core/templates/core/base.html
<!doctype html>
<!--Templatka do strony w core-->
<html>
    <head>
        <title>{%block title%}{%endblock%} | Stronka</title><!--tytuł strony-->
        <meta charset="utf-8"> 
        <meta name="viewport" content="width=device-width, initial-scale=1"><!--skalowanie doi urządzenia-->

        <script src="https://cdn.tailwindcss.com"></script><!--css do strony-->

    </head>

    <body>
        
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semibold">Stronka</a>
            <div class="space-x-6">
                <a href="#" class="text-lg hover:text-gray-900">Element</a>
                <a href="{% url 'item:browse' %}" class="text-lg hover:text-gray-900">Browse</a>
                
                {% if request.user.is_authenticated %}
                    
                    <div class="group inline-block relative">
                        <a class="px-6 py-3 text-lg hover:text-gray-900 bg-teal-500 text-white rounded-xl hover:bg-teal-700 cursor-pointer">Dashboard</a>
                        <div class="absolute left-1/2 transform -translate-x-1/2 mt-2 w-48 rounded-xl shadow-lg py-1 bg-gray-100 hidden group-hover:block" role="menu" aria-orientation="vertical" aria-labelledby="user-menu">
                        
                            <a href="{% url 'item:new' %}" class="block px-6 py-3 text-lg text-left ml-2 mr-2 text-gray-700 hover:bg-gray-200" role="menuitem">Add Item</a>
                            <a href="{% url 'dashboard:index' %}" class="block px-6 py-3 text-lg text-left ml-2 mr-2 text-gray-700 hover:bg-gray-200" role="menuitem">Your Items</a>
                            <a href="{% url 'conversation:inbox' %}" class="block px-6 py-3 text-lg text-left ml-2 mr-2 text-gray-700 hover:bg-gray-200" role="menuitem">Inbox</a>
                        
                        </div>
                    </div>
            
                    <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg hover:text-gray-900 bg-gray-500 text-white rounded-xl hover:bg-gray-700">Logout</a>
                    
                {% else %}
                    <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg hover:text-gray-900 bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a><!--przyciski do logowania-->
                    <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg hover:text-gray-900 bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
                {% endif %}
            </div>
        </nav>
        
        <div class="px-6 py-6"><!--tutaj jest zawartość strony-->
            {%block content %}
            {%endblock%}
        </div>
        
        <footer class="py-6 px-6 flex justify-between bg-gray-800"><!--stopka strony-->
            <div class="w2/3 pr-10"><!--o stronie-->
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>

                <p class="text-lg text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            </div>
            <div class="w-1/3"><!--menu strony-->
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms of use</a></li>
                </ul>
                
        </footer>

            
    </body>
</html>

web/core/templates/core/contact.html
{% extends 'core/base.html' %}
{% block title %}Contact{%endblock%}

{%block content%}
    <h1>Contact</h1>
    <p> Welcome to the Contact page</p>
{%endblock%}

web/core/templates/core/index.html
{% extends 'core/base.html' %} <!-- Rozszerza bazowy szablon HTML -->
{% block title %}Home{%endblock%} <!-- Ustawia tytuł strony na "Home" -->

{%block content%} <!-- Początek bloku zawartości -->
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl"> <!-- Kontener dla najnowszych przedmiotów -->
        <h2 class="mb-12 text-2xl text-center">Newest items</h2> <!-- Nagłówek sekcji -->
        
        <div class="grid grid-cols-3 gap-3"> <!-- Kontener siatki dla przedmiotów -->
            {% for item in items %} <!-- Pętla przez wszystkie przedmioty -->
            <div> <!-- Kontener dla pojedynczego przedmiotu -->
                <a href="{% url 'item:detail' item.id %}"> <!-- Link do szczegółów przedmiotu -->
                    <div>
                        <img src= "{{item.image.url}}" class="rounded-t-xl" style="width: 100%; height: 200px; object-fit: cover; display: block; margin: auto;"> <!-- Obraz przedmiotu -->
                    </div>
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{item.name}}</h2> <!-- Nazwa przedmiotu -->
                        <p class="text-gray-500">Price: {{item.price}} $</p> <!-- Cena przedmiotu -->
                    </div>
                </a>
            </div>
            {% endfor %} <!-- Koniec pętli przez przedmioty -->
        </div>
    </div>
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl"> <!-- Kontener dla kategorii -->
        <h2 class="mb-12 text-2xl text-center">Categories</h2> <!-- Nagłówek sekcji -->
        <div class="grid grid-cols-3 gap-3"> <!-- Kontener siatki dla kategorii -->
            {% for category in categories %} <!-- Pętla przez wszystkie kategorie -->
            <div> <!-- Kontener dla pojedynczej kategorii -->
                <a href="#">
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{category.name}}</h2> <!-- Nazwa kategorii -->
                        <p class="text-gray-500">{% if category.items.count == 1 %}1 item{% else %}{{category.items.count}} items{% endif %}</p> <!-- Liczba przedmiotów w kategorii -->
                    </div>
                </a>
            </div>
            {% endfor %} <!-- Koniec pętli przez kategorie -->
        </div>
    </div>

{%endblock%} <!-- Koniec bloku zawartości -->

web/core/templates/core/login.html
{% extends 'core/base.html' %} <!-- Rozszerza bazowy szablon HTML -->

{% block title %}Log in{%endblock%} <!-- Ustawia tytuł strony na "Signup" -->

{% block content %} <!-- Początek bloku zawartości -->
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl"> <!-- Kontener dla formularza rejestracji -->
        <h1 class="mb-6 text-3xl">Signup</h1> <!-- Nagłówek formularza -->
        <form method="post"> <!-- Początek formularza -->
            {% csrf_token %} <!-- Token CSRF dla zabezpieczenia formularza -->
            <div class="mb-3"> <!-- Kontener dla pola "Username" -->
                <label class="inline-block mb-2">Username</label><br>
                {{form.username}} <!-- Pole "Username" -->
            </div>
            <div class="mb-3"> <!-- Kontener dla pola "Password" -->
                <label class="inline-block mb-2">Password</label><br>
                {{form.password}} <!-- Pole "Password" -->
            </div>
            
            {% if form.errors or form.non_field_errors %} <!-- Jeśli są błędy formularza -->
                <div class="bg-red-100 p-6 mb-3 rounded-xl"> <!-- Kontener dla błędów -->
                    <ul> <!-- Lista błędów -->
                        {% for error in form.errors %} <!-- Pętla przez błędy -->
                            <li>{{error}}</li> <!-- Wyświetla błąd -->
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
                
            <button class="py-4 px-8 text-lg rounded-xl bg-teal-500 hover:bg-teal-700 text-white">Log In</button> <!-- Przycisk "Signup" -->

    </div>
{% endblock %} <!-- Koniec bloku zawartości -->

web/core/templates/core/logout.html
{% extends 'core/base.html' %} <!-- Rozszerza bazowy szablon HTML -->

{% block title %}Log out{%endblock%} <!-- Ustawia tytuł strony na "Signup" -->

{% block content %} <!-- Początek bloku zawartości -->
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl"> <!-- Kontener dla formularza rejestracji -->
            {% if request.user.is_authenticated %}
                <h1 class="text-3xl text-center font-bold mb-6">Are you sure you want to log out?</h1>
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="w-full bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Log out</button>
                </form>
            {% else %}
                <h1 class="text-3xl text-center font-bold mb-6">You are not logged in</h1>
            {% endif %}
     
    </div>
{% endblock %} <!-- Koniec bloku zawartości -->

web/core/templates/core/signup.html
{% extends 'core/base.html' %} <!-- Rozszerza bazowy szablon HTML -->

{% block title %}Sign up{%endblock%} <!-- Ustawia tytuł strony na "Signup" -->

{% block content %} <!-- Początek bloku zawartości -->
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl"> <!-- Kontener dla formularza rejestracji -->
        <h1 class="mb-6 text-3xl">Signup</h1> <!-- Nagłówek formularza -->
        <form method="post"> <!-- Początek formularza -->
            {% csrf_token %} <!-- Token CSRF dla zabezpieczenia formularza -->
            <div class="mb-3"> <!-- Kontener dla pola "Username" -->
                <label class="inline-block mb-2">Username</label><br>
                {{form.username}} <!-- Pole "Username" -->
            </div>
            <div class="mb-3"> <!-- Kontener dla pola "Email" -->
                <label class="inline-block mb-2">Email</label><br>
                {{form.email}} <!-- Pole "Email" -->
            </div>
            <div class="mb-3"> <!-- Kontener dla pola "Password" -->
                <label class="inline-block mb-2">Password</label><br>
                {{form.password1}} <!-- Pole "Password" -->
            </div>
            <div class="mb-3"> <!-- Kontener dl a pola "Confirm Password"-->
                <label class="inline-block mb-2">Confirm Password</label><br>
                {{form.password2}} <!-- Pole "Confirm Password" -->
            </div>
            
            {% if form.errors or form.non_field_errors %} <!-- Jeśli są błędy formularza -->
                <div class="bg-red-100 p-6 mb-3 rounded-xl"> <!-- Kontener dla błędów -->
                    <ul> <!-- Lista błędów -->
                        {% for error in form.errors %} <!-- Pętla przez błędy -->
                            <li>{{error}}</li> <!-- Wyświetla błąd -->
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
                
            <button class="py-4 px-8 text-lg rounded-xl bg-teal-500 hover:bg-teal-700 text-white">Sign Up</button> <!-- Przycisk "Signup" -->

    </div>
{% endblock %} <!-- Koniec bloku zawartości -->